driver:
  name: vagrant
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['http_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>
  synced_folders:
    - ["seedjob/", "/opt/seedjob"]
  customize:
    cpus: 2
    memory: 2048
  network:
    - - forwarded_port
      - guest: 80
        host: 9090
        auto_correct: true
    - - forwarded_port
      - guest: 8080
        host: 9091
        auto_correct: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - jenkins-chef-dsl::build-jdks
      - apt::default
      - jenkins::java
  - name: bento/centos-6.7
    run_list:
      - yum::default
      - jenkins::java
  - name: bento/centos-7.1
    run_list:
      - yum::default
      - jenkins::java

provisioner:
    name: chef_zero
    require_chef_omnibus: true
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>

suites:
  - name: jenkins-chef-dsl
    run_list:
      - jenkins-chef-dsl::default
      - jenkins-chef-dsl::proxy
        #- jenkins-chef-dsl::artifactory
    attributes:
      jenkins:
        master:
          host: localhost
          install_method: package
